### ISSUE TITLE
Generated output - security vulnerability on github

### ISSUE THREAD

**Issue by sebastianbochan** [deshaw/gulp-jsdoc3#57]
In case of generating docs by jsdoc and publish on github, Im receiving the warning about "security vulnerability: jQuery" which is kept in prettify.

**Comment by mlucool** [comment]
Hi, thanks for the feedback. Do you have a reproducer or example? From the description, it seems like the issue is best logged with [jsdoc](https://github.com/jsdoc/jsdoc) or prettify.

**Comment by sebastianbochan** [comment]
Thanks, will report there. Lets open this ticket until feedback from jsDoc.

**Comment by mlucool** [comment]
@sebastianbochan I'm closing this as this project only links gulp to the generator so there is nothing we can do here. You should continue to follow up in the related repos. Thanks again for reporting!
