### ISSUE TITLE
Gulp script doesn't produce files

### ISSUE THREAD

**Issue by netgfx** [deshaw/gulp-jsdoc3#58]
Hello,

I'm trying to produce documentation, this is the script I'm using:

```
let gulp = require('gulp');
const jsdoc = require('gulp-jsdoc3');

gulp.task('doc', function(cb) {
    const config = require('./jsdoc.json');
    gulp.src(['README.md', './source/js/classes/**/*.js', "./source/js/libs/**/*.js", "./source/js/router.js", "./source/js/utils.js", "./source/js/generic.js"], { read: false })
        .pipe(jsdoc(config, cb));
});
```

My files use es6 with `import` and `class` if it helps. But none of the files get produced, the folder and index.html and quicksearch.html do get produced however. 

The console logs this:
```
Using gulpfile C:\xampp\htdocs\myproject\gulpfile.js
Starting 'doc'...
Documented 21 files!
Finished 'doc' after 1.98 s
```
And my jsdoc is this:

```
{
    "tags": {
        "allowUnknownTags": true
    },
    "opts": {
        "destination": "./docs/gen"
    },
    "plugins": [
        "plugins/markdown"
    ],
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": false,
        "default": {
            "outputSourceFiles": true
        },
        "path": "ink-docstrap",
        "theme": "Cosmo",
        "navType": "vertical",
        "linenums": true,
        "dateFormat": "MMMM Do YYYY, h:mm:ss a"
    }
}
```

Any ideas what is going on?

**Comment by mlucool** [comment]
I'm not sure, but I'd suggest reproducing with just jsdoc on a single file to narrow it down. This [debug](https://github.com/visionmedia/debug#readme) line shows you what we ran under the hood:  https://github.com/deshaw/gulp-jsdoc3/blob/master/src/gulp-jsdoc.js#L99

Usage:
```
DEBUG='gulp-jsdoc3' gulp doc
```

From there you can try and narrow it down to what file/syntax is giving you trouble.

**Comment by netgfx** [comment]
Thanks, I ended up using https://documentation.js.org/ with no problems plus vue internal methods support.
